# docker-compose.yml
version: '3.8'

services:
  dust-predictor:
    build: .
    container_name: tashkent-dust-predictor
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      # Mount data directories for persistence
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
      # Mount Earth Engine credentials (critical!)
      - ~/.config/earthengine:/home/appuser/.config/earthengine:ro
      # Mount .env for configuration
      - ./.env:/app/.env:ro
    environment:
      - FLASK_ENV=production
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5001
      - GOOGLE_CLOUD_PROJECT=youtubecommentsapp
      - PYTHONUNBUFFERED=1
    networks:
      - dust-predictor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dust-predictor-network:
    driver: bridge